name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # এটা খুব গুরুত্বপূর্ণ, না দিলে push হবে না

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true   # GITHUB_TOKEN ব্যবহারের জন্য

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip git
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Commit APK to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          mkdir -p output-apk
          cp bin/*.apk output-apk/
          git add output-apk/*.apk || echo "Nothing to add"
          git commit -m "Add built APK" || echo "Nothing to commit"
          git push origin main

                  
